apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: Docker Hub
        api_url: https://registry.hub.docker.com
        ping: yes
        credentials: secret:argocd/dockerhub-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: argocd
type: Opaque
stringData:
  username: maheshkumars772
  password: DOCKER_PAT
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/smahesh-kumarr/argo-manifests.git"
    path: "."
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=maheshkumars772/backend
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: maheshkumars772/backend:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=maheshkumars772/frontend
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: maheshkumars772/frontend:latest
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000/api"
          ports:
            - containerPort: 3000