apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly9zbWFoZXNoLWt1bWFycjpNYWhlc2hLdW1hckBjbHVzdGVyMC50bHNidS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAvQmxvZ0FwcA==